"""sklearn-compatible ChemProp D-MPNN regressor wrapping ChemProp 1.6.1's Python API.

One class, two configurations via `use_features`:
  MPNN1 (use_features=False): graph only.
  MPNN2 (use_features=True):  graph + external precomputed features — our scaled rmoldes (316),
                              passed via --features_path with --no_features_scaling (they are
                              already RobustScaler'd upstream). This reuses the 'rdkit' featureset
                              and deviates from the paper's rdkit_2d_normalized generator
                              (2026-07-29 decision).

Validation: the paper's MPNN_public.py did a single split / no CV. We instead run this wrapper
through the project's model_validation() so MPNN gets a CV distribution like the other models —
Full (5x3) or Sample (3x1) selected by the notebook's MPNN_CV flag (which just sets
model_validation's n_splits/n_repeats). Each fit() is ONE ChemProp training (num_folds=1, with
ChemProp's own internal train/val split for early stopping).

X encoding — so sklearn cross_val_score can row-split it while keeping SMILES aligned with features:
  use_features=False: X is (n, 1),   column 0 = SMILES.
  use_features=True:  X is (n, 1+F) object array; column 0 = SMILES, columns 1: = float features.

ChemProp/torch are imported lazily inside fit/predict so importing this class is cheap and quiet.
"""

import csv
import os
import shutil
import tempfile

import numpy as np
from sklearn.base import BaseEstimator, RegressorMixin


# ChemProp 1.6.1's training-schedule defaults, pinned EXPLICITLY so that upgrading ChemProp
# (or any dependency that changes its defaults) cannot silently alter MPNN behaviour. Every value
# here was verified equal to 1.6.1's own default on 2026-08-02, so pinning is fidelity-neutral
# today — it only removes future drift risk. The architecture hyperparameters (hidden_size, depth,
# dropout, ffn_num_layers — the tuned "S14" set) are already passed explicitly in fit(); these are
# the schedule/aggregation knobs the wrapper previously left to ChemProp's implicit defaults.
# NOTE: `bias` (default False) is a store_true flag with no CLI way to force it False, so it cannot
# be pinned here and stays implicit.
_PINNED_CHEMPROP_DEFAULTS = [
    "--batch_size", "50",
    "--init_lr", "0.0001",
    "--max_lr", "0.001",
    "--final_lr", "0.0001",
    "--warmup_epochs", "2.0",
    "--activation", "ReLU",
    "--aggregation", "mean",
    "--aggregation_norm", "100",
]


class ChempropRegressor(BaseEstimator, RegressorMixin):
    """ChemProp D-MPNN as a scikit-learn regressor. Hyperparameter names mirror param_base_MPNN.

    Three feature configurations (mutually exclusive):
      MPNN1: use_features=False, features_generator=None — graph only. X is (n, 1) SMILES.
      MPNN2: use_features=True,  features_generator=None — graph + EXTERNAL precomputed features
             (our RobustScaler'd rmoldes, 316) passed via --features_path with --no_features_scaling.
             X is (n, 1+F): col 0 SMILES, cols 1: float features.
      MPNN3: use_features=False, features_generator='rdkit_2d_normalized' — graph + ChemProp's OWN
             generated rdkit_2d_normalized descriptors (200, CDF-normalized by descriptastorus).
             X is (n, 1) SMILES only — ChemProp computes the descriptors from SMILES. Uses
             --no_features_scaling (the generator is already normalized). This is the paper-faithful
             variant (Fang et al. use rdkit_2d_normalized); MPNN2 deviates by reusing our 316 rmoldes.
    """

    def __init__(self, hidden_size=300, depth=3, dropout=0.0, ffn_num_layers=2,
                 epochs=30, use_features=False, features_generator=None, metric="r2", random_state=42):
        self.hidden_size = hidden_size
        self.depth = depth
        self.dropout = dropout
        self.ffn_num_layers = ffn_num_layers
        self.epochs = epochs
        self.use_features = use_features
        self.features_generator = features_generator
        self.metric = metric
        self.random_state = random_state

    def _split_X(self, X):
        X = np.asarray(X, dtype=object)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        smiles = [str(s) for s in X[:, 0]]
        # Only MPNN2 carries external features in X; MPNN3's descriptors are generated by ChemProp
        # from SMILES, so its X is SMILES-only (feats=None) exactly like MPNN1.
        feats = X[:, 1:].astype(np.float64) if self.use_features else None
        return smiles, feats

    def _check_feature_mode(self):
        if self.use_features and self.features_generator:
            raise ValueError(
                "use_features (external features via X) and features_generator (ChemProp-generated) "
                "are mutually exclusive — set at most one."
            )

    @staticmethod
    def _write_data_csv(path, smiles, y=None):
        with open(path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["smiles", "target"] if y is not None else ["smiles"])
            if y is not None:
                for smi, yi in zip(smiles, y):
                    w.writerow([smi, float(yi)])
            else:
                for smi in smiles:
                    w.writerow([smi])

    def fit(self, X, y):
        from chemprop.args import TrainArgs
        from chemprop.train import cross_validate, run_training

        self._check_feature_mode()
        smiles, feats = self._split_X(X)
        y = np.asarray(y, dtype=float)

        self.save_dir_ = tempfile.mkdtemp(prefix="chemprop_fit_")
        train_csv = os.path.join(self.save_dir_, "train.csv")
        self._write_data_csv(train_csv, smiles, y)

        args = [
            "--data_path", train_csv,
            "--dataset_type", "regression",
            "--save_dir", self.save_dir_,
            "--hidden_size", str(self.hidden_size),
            "--depth", str(self.depth),
            "--dropout", str(self.dropout),
            "--ffn_num_layers", str(self.ffn_num_layers),
            # ffn_hidden_size defaults to hidden_size in 1.6.1; pin it to hidden_size so that
            # linkage is explicit and cannot drift on a version bump (fidelity-neutral today).
            "--ffn_hidden_size", str(self.hidden_size),
            "--epochs", str(self.epochs),
            "--metric", self.metric,
            "--num_folds", "1",
            "--seed", str(self.random_state),
            "--pytorch_seed", str(self.random_state),
            # num_workers=0: no DataLoader worker processes. Required — worker spawn breaks under
            # Jupyter / stdin and would nest inside sklearn CV's own joblib parallelism.
            "--num_workers", "0",
            "--quiet",
        ] + _PINNED_CHEMPROP_DEFAULTS
        if self.features_generator:                                    # MPNN3
            args += ["--features_generator", self.features_generator, "--no_features_scaling"]
        elif self.use_features:                                        # MPNN2
            feats_path = os.path.join(self.save_dir_, "train_feats.npz")
            np.savez(feats_path, features=feats)
            args += ["--features_path", feats_path, "--no_features_scaling"]

        cross_validate(args=TrainArgs().parse_args(args), train_func=run_training)
        return self

    def predict(self, X):
        from chemprop.args import PredictArgs
        from chemprop.train import make_predictions

        smiles, feats = self._split_X(X)
        pred_dir = tempfile.mkdtemp(prefix="chemprop_pred_")
        try:
            test_csv = os.path.join(pred_dir, "test.csv")
            preds_csv = os.path.join(pred_dir, "preds.csv")
            self._write_data_csv(test_csv, smiles)

            args = [
                "--test_path", test_csv,
                "--preds_path", preds_csv,
                "--checkpoint_dir", self.save_dir_,
                "--num_workers", "0",
            ]
            if self.features_generator:                                # MPNN3
                args += ["--features_generator", self.features_generator, "--no_features_scaling"]
            elif self.use_features:                                    # MPNN2
                feats_path = os.path.join(pred_dir, "test_feats.npz")
                np.savez(feats_path, features=feats)
                args += ["--features_path", feats_path, "--no_features_scaling"]

            raw = make_predictions(args=PredictArgs().parse_args(args))
            # make_predictions returns one list per molecule; invalid SMILES yield the string
            # 'Invalid SMILES' — the ADME set is pre-cleaned, so we expect all floats.
            return np.array([p[0] for p in raw], dtype=float)
        finally:
            shutil.rmtree(pred_dir, ignore_errors=True)

    def __del__(self):
        # best-effort cleanup of the fitted-model temp dir (bounded disk use across CV folds)
        shutil.rmtree(getattr(self, "save_dir_", ""), ignore_errors=True)


def tune_mpnn_hyperopt(X, y, use_features=False, features_generator=None,
                       num_iters=20, epochs=30, random_state=42):
    """Run ChemProp's built-in hyperopt (TPE) over its 'basic' search space and return the winning
    config as a dict of ChempropRegressor kwargs {hidden_size, depth, dropout, ffn_num_layers}.

    'basic' searches {depth, ffn_num_layers, dropout, linked_hidden_size} — matching the paper's
    default ChemProp search (S14). X is encoded exactly like ChempropRegressor (col 0 = SMILES,
    cols 1: = features when use_features). The two feature modes mirror the estimator and are
    mutually exclusive: use_features=True feeds external features via --features_path (MPNN2);
    features_generator='rdkit_2d_normalized' has ChemProp generate them (MPNN3). num_iters = number
    of trials (paper: 20; fewer for a Sample preview). Each trial trains for `epochs`.
    """
    import json

    from chemprop.args import HyperoptArgs
    from chemprop.hyperparameter_optimization import hyperopt

    if use_features and features_generator:
        raise ValueError("use_features and features_generator are mutually exclusive — set at most one.")

    probe = ChempropRegressor(use_features=use_features)   # reuse identical X-decoding
    smiles, feats = probe._split_X(X)
    y = np.asarray(y, dtype=float)

    work_dir = tempfile.mkdtemp(prefix="chemprop_hyperopt_")
    try:
        train_csv = os.path.join(work_dir, "train.csv")
        ChempropRegressor._write_data_csv(train_csv, smiles, y)
        config_path = os.path.join(work_dir, "best_config.json")

        args = [
            "--data_path", train_csv,
            "--dataset_type", "regression",
            "--epochs", str(epochs),
            "--num_iters", str(num_iters),
            "--search_parameter_keywords", "basic",
            "--config_save_path", config_path,
            "--hyperopt_checkpoint_dir", os.path.join(work_dir, "ckpt"),
            "--save_dir", os.path.join(work_dir, "runs"),
            "--num_folds", "1",
            "--num_workers", "0",
            "--seed", str(random_state),
            "--pytorch_seed", str(random_state),
            "--hyperopt_seed", str(random_state),
            "--quiet",
        ] + _PINNED_CHEMPROP_DEFAULTS
        if features_generator:                                          # MPNN3
            args += ["--features_generator", features_generator, "--no_features_scaling"]
        elif use_features:                                              # MPNN2
            feats_path = os.path.join(work_dir, "train_feats.npz")
            np.savez(feats_path, features=feats)
            args += ["--features_path", feats_path, "--no_features_scaling"]

        hyperopt(HyperoptArgs().parse_args(args))
        with open(config_path) as f:
            cfg = json.load(f)   # linked_hidden_size -> hidden_size == ffn_hidden_size
        return {
            "hidden_size": int(cfg["hidden_size"]),
            "depth": int(cfg["depth"]),
            "dropout": float(cfg["dropout"]),
            "ffn_num_layers": int(cfg["ffn_num_layers"]),
        }
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)
